apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: demo-service
  namespace: default
